/*
 * Copyright (C) 2015 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#include <linux/module.h>
#include "clkchk.h"

static const char * const off_pll_names[] = {
	"univpll",
	"mmpll",
	"msdcpll",
	"vencpll",
	"tvdpll",
	"aud1pll",
	"aud2pll",
	"lvdspll",
	NULL
};

static const char * const all_clk_names[] = {
	/* plls */
	"armpll",
	"mainpll",
	"univpll",
	"mmpll",
	"msdcpll",
	"vencpll",
	"tvdpll",
	"mpll",
	"aud1pll",
	"aud2pll",
	"lvdspll",
	/* topckgen */
	"hdmitx_dig_cts",
	"main_h546m",
	"main_h364m",
	"main_h218p4m",
	"main_h156m",
	"univ_624m",
	"univ_416m",
	"univ_249p6m",
	"univ_178p3m",
	"univ_48m",
	"apll1_ck",
	"apll2_ck",
	"clkrtc_ext",
	"clkrtc_int",
	"dmpll_ck",
	"f26m_mem_ckgen",
	"hdmi_cts_ck",
	"hdmi_cts_d2",
	"hdmi_cts_d3",
	"lvdspll_ck",
	"lvdspll_d2",
	"lvdspll_d4",
	"lvdspll_d8",
	"lvdspll_eth_ck",
	"mmpll_ck",
	"mpll_208m_ck",
	"msdcpll_ck",
	"msdcpll_d2",
	"msdcpll_d4",
	"syspll_d2",
	"syspll_d2p5",
	"syspll_d3",
	"syspll_d5",
	"syspll_d7",
	"syspll1_d2",
	"syspll1_d4",
	"syspll1_d8",
	"syspll1_d16",
	"syspll2_d2",
	"syspll2_d4",
	"syspll2_d8",
	"syspll3_d2",
	"syspll3_d4",
	"syspll4_d2",
	"syspll4_d4",
	"tvdpll_d2",
	"tvdpll_d4",
	"tvdpll_d8",
	"tvdpll_d16",
	"univpll_d2",
	"univpll_d2p5",
	"univpll_d3",
	"univpll_d5",
	"univpll_d7",
	"univpll_d26",
	"univpll1_d2",
	"univpll1_d4",
	"univpll2_d2",
	"univpll2_d4",
	"univpll2_d8",
	"univpll3_d2",
	"univpll3_d4",
	"univpll3_d8",
	"vencpll_ck",
	"apll2_div0",
	"apll2_div1",
	"axi_sel",
	"mem_sel",
	"ddrphycfg_sel",
	"mm_sel",
	"pwm_sel",
	"vdec_sel",
	"mfg_sel",
	"camtg_sel",
	"uart_sel",
	"spi_sel",
	"msdc30_0_sel",
	"msdc30_1_sel",
	"msdc30_2_sel",
	"msdc50_3_hsel",
	"msdc50_3_sel",
	"audio_sel",
	"aud_intbus_sel",
	"pmicspi_sel",
	"scp_sel",
	"atb_sel",
	"mjc_sel",
	"dpi0_sel",
	"scam_sel",
	"aud_1_sel",
	"aud_2_sel",
	"dpi1_sel",
	"ufoenc_sel",
	"ufodec_sel",
	"eth_sel",
	"onfi_sel",
	"snfi_sel",
	"hdmi_sel",
	"rtc_sel",
	/* infracfg */
	"infra_pmic_tmr",
	"infra_pmic_ap",
	"infra_pmic_md",
	"infra_pmic_conn",
	"infra_scpsys",
	"infra_sej",
	"infra_apxgpt",
	"infra_usb",
	"infra_icusb",
	"infra_gce",
	"infra_therm",
	"infra_i2c0",
	"infra_i2c1",
	"infra_i2c2",
	"infra_pwm_hclk",
	"infra_pwm1",
	"infra_pwm2",
	"infra_pwm3",
	"infra_pwm",
	"infra_uart0",
	"infra_uart1",
	"infra_uart2",
	"infra_uart3",
	"infra_usb_mcu",
	"infra_nfi_ecc66",
	"infra_nfi_66m",
	"infra_btif",
	"infra_spi",
	"infra_msdc3",
	"infra_msdc1",
	"infra_msdc2",
	"infra_msdc0",
	"infra_gcpu",
	"infra_auxadc",
	"infra_cpum",
	"infra_irrx",
	"infra_ufo",
	"infra_cec",
	"infra_cec_26m",
	"infra_nfi_bclk",
	"infra_nfi_ecc",
	"infra_ap_dma",
	"infra_xiu",
	"infra_devapc",
	"infra_xiu2ahb",
	"infra_l2c_sram",
	"infra_eth_50m",
	"infra_debugsys",
	"infra_audio",
	"infra_eth_25m",
	"infra_nfi",
	"infra_onfi",
	"infra_snfi",
	"infra_eth",
	"infra_dramc_26m",
	"osc_ck",
	"osc_d8",
	"osc_d16",
	"clk26m_d8",
	"eth_d2",
	"onfi_d2",
	"clk13m",
	"infra_uart0_sel",
	"infra_uart1_sel",
	"infra_uart2_sel",
	"infra_uart3_sel",
	"infra_spi_sel",
	"infra_dramc_sel",
	"infra_ulp_sel",
	"infra_eth_sel",
	"infra_nfi_sel",
	/* mfgsys */
	"mfg_ff",
	"mfg_dw",
	"mfg_tx",
	"mfg_mx",
	/* imgsys */
	"img_larb2_smi",
	"img_jpgenc",
	"img_cam_smi",
	"img_cam_cam",
	"img_sen_tg",
	"img_sen_cam",
	"img_cam_sv",
	/* mmsys */
	"mm_smi_comoon",
	"mm_smi_larb0",
	"mm_cam_mdp",
	"mm_mdp_rdma",
	"mm_mdp_rsz0",
	"mm_mdp_rsz1",
	"mm_mdp_tdshp",
	"mm_mdp_wdma",
	"mm_mdp_wrot",
	"mm_fake_eng",
	"mm_disp_ovl0",
	"mm_disp_ovl1",
	"mm_disp_rdma0",
	"mm_disp_rdma1",
	"mm_disp_wdma0",
	"mm_disp_color",
	"mm_disp_ccorr",
	"mm_disp_aal",
	"mm_disp_gamma",
	"mm_disp_dither",
	"mm_disp_ufoe",
	"mm_larb4_mm",
	"mm_larb4_mjc",
	"mm_disp_wdma1",
	"mm_ufodrdma0_l0",
	"mm_ufodrdma0_l1",
	"mm_ufodrdma0_l2",
	"mm_ufodrdma0_l3",
	"mm_ufodrdma1_l0",
	"mm_ufodrdma1_l1",
	"mm_ufodrdma1_l2",
	"mm_ufodrdma1_l3",
	"mm_disp_pwm0mm",
	"mm_disp_pwm026m",
	"mm_dsi0_engine",
	"mm_dsi0_digital",
	"mm_dpi_pixel",
	"mm_dpi_engine",
	"mm_lvds_pixel",
	"mm_lvds_cts",
	"mm_dpi1_pixel",
	"mm_dpi1_engine",
	"mm_hdmi_pixel",
	"mm_hdmi_spdif",
	"mm_hdmi_audio",
	"mm_hdmi_pllck",
	"mm_disp_dsc_eng",
	"mm_disp_dsc_mem",
	/* vdecsys */
	"vdec_cken",
	"vdec_larb_cken",
	/* vencsys */
	"venc_cke0",
	"venc_cke1",
	"venc_cke2",
	"venc_cke3",
	/* audiosys */
	"aud_afe",
	"aud_i2s",
	"aud_22m",
	"aud_24m",
	"aud_spdf2",
	"aud_apll2_tnr",
	"aud_apll_tnr",
	"aud_hdmi",
	"aud_spdf",
	"aud_adc",
	"aud_dac",
	"aud_dac_predis",
	"aud_tml",
	"aud_ahb_idl_ex",
	"aud_ahb_idl_in",
	/* end */
	NULL
};

static const char * const compatible[] = {"mediatek,mt8163", NULL};

static struct clkchk_cfg_t cfg = {
	.aee_excp_on_fail = false,
	.warn_on_fail = true,
	.compatible = compatible,
	.off_pll_names = off_pll_names,
	.all_clk_names = all_clk_names,
};

static int __init clkchk_platform_init(void)
{
	return clkchk_init(&cfg);
}
subsys_initcall(clkchk_platform_init);
