ccflags-y += -I$(srctree)/drivers/misc/mediatek/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8163/include/mach/
obj-y	:=  bmi160_gyro.o
