# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y   +=  alsps.o
obj-y   +=  alsps_factory.o
obj-y   +=  aal_control.o

obj-$(CONFIG_MTK_STK3X1X_STK)	+=  stk3x1x_stk/
obj-$(CONFIG_MTK_JSA1214)	+=  jsa1214/
