#include "cmdq_def.h"


/* use to generate [CMDQ_ENGINE_ENUM_id and name] mapping for status print */
#define CMDQ_FOREACH_STATUS_MODULE_PRINT(ACTION)\
	ACTION(CMDQ_ENG_ISP_IMGI,   ISP_IMGI) \
	ACTION(CMDQ_ENG_MDP_RDMA0,  MDP_RDMA0) \
	ACTION(CMDQ_ENG_MDP_RSZ0,   MDP_RSZ0) \
	ACTION(CMDQ_ENG_MDP_RSZ1,   MDP_RSZ1) \
	ACTION(CMDQ_ENG_MDP_TDSHP0, MDP_TDSHP0) \
	ACTION(CMDQ_ENG_MDP_WROT0,  MDP_WROT0) \
	ACTION(CMDQ_ENG_MDP_WDMA,   MDP_WDMA)

