# drivers/cmdq

ccflags-y += -I$(srctree)/drivers/misc/mediatek/cmdq/hv1

# Enable MET
# ccflags-y += -DMET_USER_EVENT_SUPPORT

obj-y += cmdq_mdp.o
obj-y += cmdq_core_idv.o
obj-y += cmdq_platform_idv.o