#ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8163/include/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8163/include/mach/

ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-y	:=  bma253.o

