ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8163/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8163/include/mach/

obj-y	:=  tmp103.o
