ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8163/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt8163/include/mach/

obj-y	:=  stk3x1x.o
