# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y   +=  gyroscope.o gyro_factory.o

obj-$(CONFIG_MTK_LSM6DS3GY)   +=  lsm6ds3gy/
